import { spawnSync } from "node:child_process";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const cloudflareGlue = `/* Generated by scripts/build-router-wasm.ts. */
import * as imports from "./maildesk_router_bg.js";
import wasmModule from "./maildesk_router_bg.wasm";

const importObject = {
  "./maildesk_router_bg.js": imports,
};

let instance;
if (typeof wasmModule === "string") {
  const bunRuntime = globalThis.Bun;
  if (!bunRuntime) {
    throw new Error("maildesk router WASM path requires the Bun test runtime");
  }
  const bytes = await bunRuntime.file(wasmModule).arrayBuffer();
  const result = await WebAssembly.instantiate(bytes, importObject);
  instance = result.instance;
} else {
  instance = new WebAssembly.Instance(wasmModule, importObject);
}

imports.__wbg_set_wasm(instance.exports);

export * from "./maildesk_router_bg.js";
`;

export async function buildRouterWasm(outDir = join(root, "generated", "router-wasm")): Promise<void> {
  const resolvedOutDir = resolve(outDir);
  const build = spawnSync(
    "wasm-pack",
    [
      "build",
      "crates/maildesk-router",
      "--target",
      "bundler",
      "--release",
      "--out-dir",
      resolvedOutDir,
    ],
    { cwd: root, encoding: "utf8" },
  );

  if (build.stdout) process.stdout.write(build.stdout);
  if (build.stderr) process.stderr.write(build.stderr);
  if (build.status !== 0) {
    throw new Error(`maildesk router WASM build failed with status ${build.status ?? "unknown"}`);
  }

  await Bun.write(join(resolvedOutDir, "maildesk_router.js"), cloudflareGlue);
}

function selectedOutDir(argv: string[]): string {
  const index = argv.indexOf("--out-dir");
  if (index === -1) return join(root, "generated", "router-wasm");
  const value = argv[index + 1];
  if (!value || !isAbsolute(value)) {
    throw new Error("--out-dir must name one absolute directory");
  }
  if (index + 2 !== argv.length) {
    throw new Error("unexpected build-router-wasm arguments");
  }
  return value;
}

if (import.meta.main) {
  try {
    await buildRouterWasm(selectedOutDir(process.argv.slice(2)));
    console.log("maildesk router WASM ready");
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
