import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, "generated", "router-wasm");

const build = spawnSync(
  "wasm-pack",
  [
    "build",
    "crates/maildesk-router",
    "--target",
    "bundler",
    "--release",
    "--out-dir",
    "../../generated/router-wasm",
  ],
  { cwd: root, encoding: "utf8" },
);

if (build.stdout) process.stdout.write(build.stdout);
if (build.stderr) process.stderr.write(build.stderr);
if (build.status !== 0) {
  console.error("maildesk router WASM build failed");
  process.exit(build.status ?? 1);
}

const cloudflareGlue = `/* Generated by scripts/build-router-wasm.ts. */
import * as imports from "./maildesk_router_bg.js";
import wasmModule from "./maildesk_router_bg.wasm";

const importObject = {
  "./maildesk_router_bg.js": imports,
};

let instance;
if (typeof wasmModule === "string") {
  const bunRuntime = globalThis.Bun;
  if (!bunRuntime) {
    throw new Error("maildesk router WASM path requires the Bun test runtime");
  }
  const bytes = await bunRuntime.file(wasmModule).arrayBuffer();
  const result = await WebAssembly.instantiate(bytes, importObject);
  instance = result.instance;
} else {
  instance = new WebAssembly.Instance(wasmModule, importObject);
}

imports.__wbg_set_wasm(instance.exports);

export * from "./maildesk_router_bg.js";
`;

await Bun.write(join(outDir, "maildesk_router.js"), cloudflareGlue);
console.log("maildesk router WASM ready");
